packages:
  - backend/
  - frontend/

overrides:
  '@octokit/endpoint@>=9.0.5 <9.0.6': '>=9.0.6'
  '@octokit/plugin-paginate-rest@>=9.3.0-beta.1 <11.4.1': '>=11.4.1'
  '@octokit/request-error@>=1.0.0 <5.1.1': '>=5.1.1'
  '@octokit/request@>=1.0.0 <8.4.1': '>=8.4.1'
  ajv@<6.14.0: '>=6.14.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  micromatch@<4.0.8: '>=4.0.8'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tmp@<=0.2.3: '>=0.2.4'
