import type { NotePlaceholder } from "./placeholder.type";

export const notePlaceholders: NotePlaceholder[] = [
  {
    id: 1,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Kurashina Asuka",
    quote: "The sky is so big, there's room for everyone's dreams.",
  },
  {
    id: 2,
    series: "Find Love or Die Trying",
    character: "Kat",
    quote: "Is it really love if there's no risk involved?",
  },
  {
    id: 3,
    series: "Doki Doki Literature Club",
    character: "Monika",
    quote: "Every day, I imagine a future where I can be with you.",
  },
  {
    id: 4,
    series: "Steins;Gate",
    character: "Makise Kurisu",
    quote: "Every brilliant day should be lived for those who passed away.",
  },
  {
    id: 5,
    series: "Frieren: Beyond Journey's End",
    character: "Himmel",
    quote:
      "It's not about how long you lived, but what you did with the time you had.",
  },
  {
    id: 6,
    series: "Clannad",
    character: "Okazaki Tomoya",
    quote: "I hate this town. It's too full of memories I'd rather forget.",
  },
  {
    id: 7,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Tobisawa Misaki",
    quote: "Udon is the food of the gods. Also, flying is okay, I guess.",
  },
  {
    id: 8,
    series: "Oshi no Ko",
    character: "Hoshino Ai",
    quote: "Lies are the most exquisite form of love.",
  },
  {
    id: 9,
    series: "Code Geass",
    character: "Lelouch vi Britannia",
    quote:
      "If the king doesn't lead, how can he expect his subordinates to follow?",
  },
  {
    id: 10,
    series: "Muv-Luv Alternative",
    character: "Mitsurugi Meiya",
    quote: "To know the value of life, one must first face death.",
  },
  {
    id: 11,
    series: "The House in Fata Morgana",
    character: "Michel",
    quote: "We are all prisoners of our own pasts.",
  },
  {
    id: 12,
    series: "Bocchi the Rock!",
    character: "Ijichi Nijika",
    quote: "Even if nobody watches, we'll play our hearts out.",
  },
  {
    id: 13,
    series: "Violet Evergarden",
    character: "Violet Evergarden",
    quote: "I want to know what 'I love you' means.",
  },
  {
    id: 14,
    series: "Fate/stay night",
    character: "Saber",
    quote: "Are you my Master?",
  },
  {
    id: 15,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Arisaka Mashiro",
    quote: "I'll do my best to support you, even if I'm a bit clumsy.",
  },
  {
    id: 16,
    series: "Doki Doki Literature Club",
    character: "Sayori",
    quote: "You really do care about me, don't you?",
  },
  {
    id: 17,
    series: "Find Love or Die Trying",
    character: "Allie",
    quote: "You can't spell 'slaughter' without 'laughter'!",
  },
  {
    id: 18,
    series: "Monogatari Series",
    character: "Oshino Shinobu",
    quote: "It's difficult to be a monster, but it's harder to be human.",
  },
  {
    id: 19,
    series: "Lycoris Recoil",
    character: "Nishikigi Chisato",
    quote: "Doing what you enjoy is the most important thing!",
  },
  {
    id: 20,
    series: "Steins;Gate",
    character: "Hashida Itaru",
    quote: "I'm not a pervert! I'm a gentleman with refined tastes!",
  },
  {
    id: 21,
    series: "Clannad",
    character: "Furukawa Nagisa",
    quote: "The world is beautiful. Even if you're full of tears and sadness.",
  },
  {
    id: 22,
    series: "Your Name",
    character: "Miyamizu Mitsuha",
    quote: "I'm always looking for someone... a person I've never met.",
  },
  {
    id: 23,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Ichinose Rika",
    quote: "Strict discipline leads to the best flight paths.",
  },
  {
    id: 24,
    series: "Doki Doki Literature Club",
    character: "Yuri",
    quote: "I just want to cut through the skin and see what's inside.",
  },
  {
    id: 25,
    series: "Fate/stay night",
    character: "Tohsaka Rin",
    quote:
      "The world is just another word for the things you can reach with your hands.",
  },
  {
    id: 26,
    series: "Muv-Luv Alternative",
    character: "Kagami Sumika",
    quote: "I'll wait for you, no matter how many worlds I have to cross.",
  },
  {
    id: 27,
    series: "Oshi no Ko",
    character: "Arima Kana",
    quote: "I'll become your star, even if it kills me.",
  },
  {
    id: 28,
    series: "Cowboy Bebop",
    character: "Spike Spiegel",
    quote: "Whatever happens, happens.",
  },
  {
    id: 29,
    series: "Bocchi the Rock!",
    character: "Yamada Ryo",
    quote: "Abandoning your personality is the same as dying.",
  },
  {
    id: 30,
    series: "Find Love or Die Trying",
    character: "Terra",
    quote: "Science is the only thing that doesn't lie to you.",
  },
  {
    id: 31,
    series: "Angel Beats!",
    character: "Tachibana Kanade",
    quote: "Thank you for giving me a life.",
  },
  {
    id: 32,
    series: "Steins;Gate",
    character: "Shiina Mayuri",
    quote: "Tutturu! Okarin, you look so serious!",
  },
  {
    id: 33,
    series: "Fate/Zero",
    character: "Emiya Kiritsugu",
    quote: "To save one life is to abandon another.",
  },
  {
    id: 34,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Aoi Madoka",
    quote: "Coach, the team is ready when you are.",
  },
  {
    id: 35,
    series: "Doki Doki Literature Club",
    character: "Natsuki",
    quote: "Manga is literature!",
  },
  {
    id: 36,
    series: "Cyberpunk: Edgerunners",
    character: "David Martinez",
    quote: "I'm built different. I'll take you to the moon.",
  },
  {
    id: 37,
    series: "Oshi no Ko",
    character: "Hoshino Ruby",
    quote: "I want to see the view Mom saw from the top.",
  },
  {
    id: 38,
    series: "Fate/stay night",
    character: "Archer",
    quote: "I am the bone of my sword. Steel is my body and fire is my blood.",
  },
  {
    id: 39,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Inui Saki",
    quote: "Strength is the only thing that matters in the sky.",
  },
  {
    id: 40,
    series: "Fate/stay night",
    character: "Illyasviel von Einzbern",
    quote: "I'm going to be a big sister, so I have to be strong.",
  },
  {
    id: 41,
    series: "Frieren: Beyond Journey's End",
    character: "Fern",
    quote: "Mr. Stark, you're being a coward again.",
  },
  {
    id: 42,
    series: "Code Geass",
    character: "Kururugi Suzaku",
    quote: "A victory won through dishonest means is no victory at all.",
  },
  {
    id: 43,
    series: "Violet Evergarden",
    character: "Benedict Blue",
    quote: "Postmen deliver more than just letters; they deliver hearts.",
  },
  {
    id: 44,
    series: "Steins;Gate",
    character: "Amane Suzuha",
    quote: "I'm a soldier from the future. And the future is a nightmare.",
  },
  {
    id: 45,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Hosaka Minori",
    quote: "Flying is fun, but reporting on it is even better!",
  },
  {
    id: 46,
    series: "Clannad",
    character: "Ichinose Kotomi",
    quote:
      "The day before yesterday I saw a rabbit, and yesterday a deer, and today, you.",
  },
  {
    id: 47,
    series: "Oshi no Ko",
    character: "Mem-cho",
    quote: "You're never too old to chase your idol dreams!",
  },
  {
    id: 48,
    series: "Sukitte Ii Na Yo",
    character: "Mei Tachibana",
    quote:
      "Someday, maybe you'll find someone like you to share your pain with. I can’t tell you when that will happen.... But the important thing is to not reject them.",
  },
  {
    id: 49,
    series: "Lycoris Recoil",
    character: "Nakahara Mizuki",
    quote: "Is there no handsome guy who wants to marry me?",
  },
  {
    id: 50,
    series: "Bocchi the Rock!",
    character: "Kita Ikuyo",
    quote: "Kita-aura! Let's shine together!",
  },
  {
    id: 51,
    series: "Find Love or Die Trying",
    character: "Yumi",
    quote: "Being on a reality show is harder than it looks.",
  },
  {
    id: 52,
    series: "Higurashi When They Cry",
    character: "Ryuugu Rena",
    quote: "I want to take it home!",
  },
  {
    id: 53,
    series: "Katawa Shoujo",
    character: "Ikezawa Hanako",
    quote: "Reading is the only way I can travel without moving.",
  },
  {
    id: 54,
    series: "Little Busters!",
    character: "Natsume Kyousuke",
    quote: "Mission Start!",
  },
  {
    id: 55,
    series: "Steins;Gate",
    character: "Okabe Rintaro",
    quote: "I am Mad Scientist, Hououin Kyouma! It's so cool! Sunuvabitch!",
  },
  {
    id: 56,
    series: "Fate/stay night",
    character: "Emiya Shirou",
    quote: "People die if they are killed.",
  },
  {
    id: 57,
    series: "Anohana: The Flower We Saw That Day",
    character: "Menma",
    quote: "You found me.",
  },
  {
    id: 58,
    series: "Grimgar of Fantasy and Ash",
    character: "Haruhiro",
    quote: "Tomorrow isn't promised, so we have to live for today.",
  },
  {
    id: 59,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Madoka Aoi",
    quote: "The blue sky is waiting for us.",
  },
  {
    id: 60,
    series: "Doki Doki Literature Club",
    character: "MC",
    quote: "I just wanted to join a club for some cupcakes.",
  },
  {
    id: 61,
    series: "Clannad: After Story",
    character: "Okazaki Ushio",
    quote: "First thing I found. Daddy's treasure.",
  },
  {
    id: 62,
    series: "Oregairu",
    character: "Hikigaya Hachiman",
    quote: "I want something real.",
  },
  {
    id: 63,
    series: "Re:Zero",
    character: "Rem",
    quote: "Even if you are the only one who hates yourself, I will love you.",
  },
  {
    id: 64,
    series: "White Album 2",
    character: "Ogiso Setsuna",
    quote: "Why did it have to be like this?",
  },
  {
    id: 65,
    series: "Air",
    character: "Kamio Misuzu",
    quote: "Gao... I'll try my best tomorrow too.",
  },
  {
    id: 66,
    series: "Kanon",
    character: "Tsukimiya Ayu",
    quote: "Uguu!",
  },
  {
    id: 67,
    series: "Toradora!",
    character: "Aisaka Taiga",
    quote: "It's a dragon and a tiger. They've always been equals.",
  },
  {
    id: 68,
    series: "Sword Art Online",
    character: "Kirito",
    quote: "No matter what, I will get us back to the real world.",
  },
  {
    id: 69,
    series: "Fate/Grand Order: Babylonia",
    character: "Gilgamesh",
    quote: "Behold my works, and despair!",
  },
  {
    id: 70,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Aoi Shion",
    quote: "The FC world is deeper than you think.",
  },
  {
    id: 71,
    series: "Find Love or Die Trying",
    character: "Allie",
    quote: "Don't worry, the cameras are always rolling.",
  },
  {
    id: 72,
    series: "Steins;Gate 0",
    character: "Hiyajo Maho",
    quote: "Science is the bridge between dreams and reality.",
  },
  {
    id: 73,
    series: "Plastic Memories",
    character: "Isla",
    quote:
      "I hope that one day, you will be reunited with the person you cherish.",
  },
  {
    id: 74,
    series: "Your Lie in April",
    character: "Miyazono Kaori",
    quote: "Was I able to live inside someone's heart?",
  },
  {
    id: 75,
    series: "Danganronpa",
    character: "Monokuma",
    quote: "Puhuhu! It's punishment time!",
  },
  {
    id: 76,
    series: "Rewrite",
    character: "Tennouji Kotarou",
    quote: "I will rewrite the fate of this world.",
  },
  {
    id: 77,
    series: "Doki Doki Literature Club",
    character: "Monika",
    quote: "You're my only sunshine.",
  },
  {
    id: 78,
    series: "Fate/stay night",
    character: "Lancer",
    quote: "Heroes always die because of unreasonable orders.",
  },
  {
    id: 79,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Tobisawa Misaki",
    quote: "Let's go eat some udon after this.",
  },
  {
    id: 80,
    series: "No Game No Life",
    character: "Sora",
    quote: "Blank never loses.",
  },
  {
    id: 81,
    series: "Kaguya-sama: Love is War",
    character: "Fujiwara Chika",
    quote: "Love is war, and I'm the chaos factor!",
  },
  {
    id: 82,
    series: "Psycho-Pass",
    character: "Tsunemori Akane",
    quote: "The law doesn't protect people. People protect the law.",
  },
  {
    id: 83,
    series: "Muv-Luv",
    character: "Shirogane Takeru",
    quote: "I'll save everyone this time. I swear it.",
  },
  {
    id: 84,
    series: "Find Love or Die Trying",
    character: "Terra",
    quote: "Emotions are just chemical reactions.",
  },
  {
    id: 85,
    series: "Steins;Gate",
    character: "Urushibara Luka",
    quote: "But... he's a guy.",
  },
  {
    id: 86,
    series: "Clannad",
    character: "Ibuki Fuko",
    quote: "Starfish are the best!",
  },
  {
    id: 87,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Kurashina Asuka",
    quote: "I love flying more than anything!",
  },
  {
    id: 88,
    series: "Doki Doki Literature Club",
    character: "Sayori",
    quote: "I just want everyone to be happy.",
  },
  {
    id: 89,
    series: "Fate/stay night",
    character: "Tohsaka Rin",
    quote: "Don't underestimate a magus.",
  },
  {
    id: 90,
    series: "Oshi no Ko",
    character: "Hoshino Ai",
    quote: "I'll love you forever, even if it's a lie.",
  },
  {
    id: 91,
    series: "Bocchi the Rock!",
    character: "Gotoh Hitori",
    quote: "I want to be in a band because I have no friends!",
  },
  {
    id: 92,
    series: "Violet Evergarden",
    character: "Gilbert Bougainvillea",
    quote: "From the bottom of my heart, I love you.",
  },
  {
    id: 93,
    series: "Angel Beats!",
    character: "Otonashi Yuzuru",
    quote: "Our lives were real.",
  },
  {
    id: 94,
    series: "Cyberpunk: Edgerunners",
    character: "Lucy",
    quote: "I don't want you to die. That's my only dream.",
  },
  {
    id: 95,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Arisaka Mashiro",
    quote: "I'll protect my senpai!",
  },
  {
    id: 96,
    series: "Steins;Gate",
    character: "Faris Nyannyan",
    quote: "The world is full of conspiracies, nyan!",
  },
  {
    id: 97,
    series: "Find Love or Die Trying",
    character: "Kat",
    quote: "Let's see who survives the final rose.",
  },
  {
    id: 98,
    series: "Doki Doki Literature Club",
    character: "Yuri",
    quote: "Would you like to read with me?",
  },
  {
    id: 99,
    series: "Fate/stay night",
    character: "Saber",
    quote: "My sword is at your service.",
  },
  {
    id: 100,
    series: "Aokana: Four Rhythms Across the Blue",
    character: "Tobisawa Misaki",
    quote: "Udon... is life.",
  },
];
