const reservedUsernameList: string[] = [
  "ao-note",
  "ao_note",
  "admin",
  "administrator",
  "root",
  "system",
  "support",
  "help",
  "contact",
  "info",
  "moderator",
  "staff",
  "owner",
  "manager",
  "superuser",
  "operator",
  "webmaster",
  "security",
  "service",
  "api",
  "user",
  "username",
  "test",
  "guest",
  "null",
  "undefined",
  "void",
  "anonymous",
  "member",
  "login",
  "logout",
  "signup",
] as const;

export const RESERVED_USERNAMES_SET = new Set<string>(reservedUsernameList);
